name: Sync Docs to Wiki

on:
  push:
    branches:
      - Beta
    paths:
      - 'docs/**'
  release:
    types: [published]

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: github-docs-to-wiki
        uses: cmbrose/github-docs-to-wiki@v0.20